### ISSUE TITLE
No download

### ISSUE THREAD

**Issue by WellingtonMonteiro** [Slyyxp/Slyyxp#1]
OtotoyPy does not work for any albums .... only personal payment collection.

![97602291-bf66a800-19d0-11eb-9145-9dac6b125377](https://user-images.githubusercontent.com/31768953/97689380-399f3700-1a7a-11eb-8c44-c0753e53a0c7.png)

**Comment by Slyyxp** [comment]
This is my profile repo, not the Ototoy repo.
Ototoy is patched and repository is deleted.
